#!/bin/bash -l 
#SBATCH -n 1
#SBATCH -p RM
#SBATCH -t 00:01:00 
#SBATCH -J Blocked_job
#SBATCH -o MyBlockedOutputFile.%j.out
#SBATCH -e MyBlockedErrorFile.%j.err

make BSIZE=$BLOCK_SIZE > block_experiment_compilerNotes"$BLOCK_SIZE".txt
./benchmark-blocked > block_experiment_benchResults"$BLOCK_SIZE".txt
